// Groups
export const GROUP_ADD = 'ADMIN/GROUP_ADD';
export const GROUP_DELETE = 'ADMIN/GROUP_DELETE';
export const GROUP_UPDATE_INFO = 'ADMIN/GROUP_UPDATE_INFO';
export const GROUP_LIST = 'ADMIN/GROUP_LIST';

// Check groups
export const GROUP_MEMBERS_GET = 'ADMIN/GROUP_MEMBERS_GET';
export const CHECK_THING = 'ADMIN/CHECK_THING';
export const CHECK_STEP = 'ADMIN/CHECK_STEP';
export const CHECK_STATUS = 'ADMIN/CHECK_STATUS';

// Check members
export const CHECK_MEMBERS_ALL = 'ADMIN/CHECK_MEMBERS_ALL';
export const CHECK_MEMBERS_WITH_INFO = 'ADMIN/CHECK_MEMBERS_WITH_INFO';
export const CHECK_MEMBERS_CLOSED = 'ADMIN/CHECK_MEMBERS_CLOSED';
export const CHECK_MEMBERS_BANNED = 'ADMIN/CHECK_MEMBERS_BANNED';
export const CHECK_MEMBERS_DELETED = 'ADMIN/CHECK_MEMBERS_DELETED';
export const CHECK_MEMBERS_SELLER = 'ADMIN/CHECK_MEMBERS_SELLER';

// Lists settings
export const LIST_SETTINGS_LIMIT_ITEMS = 'LIST_SETTINGS_LIMIT_ITEMS';
export const LIST_SETTINGS_SKIP_ITEMS = 'LIST_SETTINGS_SKIP_ITEMS';
export const LIST_SETTINGS_SORT_ITEMS = 'LIST_SETTINGS_SORT_ITEMS';
export const LIST_SETTINGS_SEARCH_TEXT = 'LIST_SETTINGS_SEARCH_TEXT';
export const LIST_SETTINGS_FETCHED_PART_ITEMS = 'LIST_SETTINGS_FETCHED_PART_ITEMS';
export const LIST_SETTINGS_TOTAL_ITEMS = 'LIST_SETTINGS_TOTAL_ITEMS';
export const LIST_SETTINGS_LOAD_MORE = 'LIST_SETTINGS_LOAD_MORE';
export const LIST_SETTINGS_MEMBER_STATUS = 'LIST_SETTINGS_MEMBER_STATUS';
export const LIST_SETTINGS_MEMBER_COUNTRY = 'LIST_SETTINGS_MEMBER_COUNTRY';
