export const types = {
    // Groups
    GROUP_ADD: 'ADMIN/GROUP_ADD',
    GROUP_DELETE: 'ADMIN/GROUP_DELETE',
    GROUP_UPDATE_INFO: 'ADMIN/GROUP_UPDATE_INFO',
    GROUP_LIST: 'ADMIN/GROUP_LIST',

    // // Photos
    // FETCH_PHOTOS_ASYNC: 'PHOTOS/FETCH_PHOTOS_ASYNC',
    // FILL_PHOTOS: 'PHOTOS/FILL_PHOTOS',

    // Favorites
    FETCH_FAVORITES_LIST: 'FAVORITE/FETCH_FAVORITES_LIST',
    FILL_FAVORITES: 'FAVORITE/FILL_FAVORITES',
    FILL_FAVORITE_ALBUMS: 'FAVORITE/FILL_FAVORITE_ALBUMS',
    FILL_FAVORITE_MEMBERS: 'FAVORITE/FILL_FAVORITE_MEMBERS',
    FILL_FAVORITE_PHOTOS: 'FAVORITE/FILL_FAVORITE_PHOTOS',

    // Check groups
    GROUP_MEMBERS_GET: 'ADMIN/GROUP_MEMBERS_GET',
    CHECK_THING: 'ADMIN/CHECK_THING',
    CHECK_STEP: 'ADMIN/CHECK_STEP',
    CHECK_STATUS: 'ADMIN/CHECK_STATUS',

    // Check members
    CHECK_MEMBERS_ALL: 'ADMIN/CHECK_MEMBERS_ALL',
    CHECK_MEMBERS_WITH_INFO: 'ADMIN/CHECK_MEMBERS_WITH_INFO',
    CHECK_MEMBERS_CLOSED: 'ADMIN/CHECK_MEMBERS_CLOSED',
    CHECK_MEMBERS_BANNED: 'ADMIN/CHECK_MEMBERS_BANNED',
    CHECK_MEMBERS_DELETED: 'ADMIN/CHECK_MEMBERS_DELETED',
    CHECK_MEMBERS_SELLER: 'ADMIN/CHECK_MEMBERS_SELLER',

    // Lists settings
    LIST_SETTINGS_LIMIT_ITEMS: 'LIST_SETTINGS_LIMIT_ITEMS',
    LIST_SETTINGS_SKIP_ITEMS: 'LIST_SETTINGS_SKIP_ITEMS',
    LIST_SETTINGS_SORT_ITEMS: 'LIST_SETTINGS_SORT_ITEMS',
    LIST_SETTINGS_SEARCH_TEXT: 'LIST_SETTINGS_SEARCH_TEXT',
    LIST_SETTINGS_FETCHED_PART_ITEMS: 'LIST_SETTINGS_FETCHED_PART_ITEMS',
    LIST_SETTINGS_TOTAL_ITEMS: 'LIST_SETTINGS_TOTAL_ITEMS',
    LIST_SETTINGS_LOAD_MORE: 'LIST_SETTINGS_LOAD_MORE',
    LIST_SETTINGS_MEMBER_STATUS: 'LIST_SETTINGS_MEMBER_STATUS',
    LIST_SETTINGS_MEMBER_COUNTRY: 'LIST_SETTINGS_MEMBER_COUNTRY'
};
